# Generated by Django 3.2 on 2022-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='resource',
            field=models.IntegerField(),
        ),
    ]
