# Generated by Django 3.2 on 2022-03-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0002_alter_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_professor', models.IntegerField()),
                ('deliveryDate', models.DateTimeField()),
                ('file', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('professorCommentary', models.CharField(max_length=500)),
                ('studentCommentary', models.CharField(max_length=500)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.course')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('routeResource', models.CharField(max_length=100)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.course')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicies_PrivacyPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_privacyPermission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.privacypermission')),
                ('id_privacyPolicy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.privacypolicy')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_student', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('id_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('courseRole', models.CharField(max_length=20)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.course')),
            ],
        ),
    ]
