# Generated by Django 3.2 on 2022-03-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0002_alter_exercise_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.resource'),
        ),
    ]
