# Generated by Django 3.2 on 2022-04-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrdelivery',
            name='delivery_date',
        ),
    ]
