# Generated by Django 3.2 on 2022-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrqualification',
            name='professor_commentary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vrqualification',
            name='student_commentary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
