# Generated by Django 3.2 on 2022-03-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='vrdelivery',
            name='performance_data',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
