# Generated by Django 3.2 on 2022-04-06 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0002_auto_20220406_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrqualification',
            name='professor_commentary',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vrqualification',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vrqualification',
            name='student_commentary',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
