# Generated by Django 3.2 on 2022-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0002_alter_vrqualification_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
