# Generated by Django 3.2 on 2022-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0003_auto_20220317_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='deliveryDate',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='professorCommentary',
            new_name='professor_commentary',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='studentCommentary',
            new_name='student_commentary',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='courseRole',
            new_name='course_role',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='routeResource',
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(default='asd', upload_to='files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='exercise_description',
            field=models.CharField(default='asd', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
