# Generated by Django 3.2 on 2022-04-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0003_alter_delivery_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vrqualification',
            old_name='VRTask',
            new_name='vr_task',
        ),
    ]
