# Generated by Django 3.2 on 2022-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0004_auto_20220321_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('VR', 'VR'), ('NORMAL', 'Normal')], default='NORMAL', max_length=30),
        ),
    ]
