# Generated by Django 3.2 on 2022-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exerciseVersion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
