# Generated by Django 3.2 on 2022-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('NO_DELIVERED', 'No delivered')], default='NO_DELIVERED', max_length=40),
        ),
    ]
