# Generated by Django 3.2 on 2022-03-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0008_task_exerciseversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='exerciseVersion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.CreateModel(
            name='VRTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_description', models.CharField(max_length=500)),
                ('exercise_version', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.course')),
            ],
        ),
        migrations.CreateModel(
            name='VRDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_exercise_was_done', models.DateTimeField()),
                ('passed_items', models.IntegerField()),
                ('failed_items', models.IntegerField()),
                ('score', models.IntegerField()),
                ('performance_data', models.FileField(upload_to='files')),
                ('exercise_version', models.IntegerField()),
                ('professor_commentary', models.CharField(max_length=500)),
                ('student_commentary', models.CharField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vr_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroomvr.vrtask')),
            ],
        ),
    ]
