# Generated by Django 3.2 on 2022-03-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0009_auto_20220328_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='exercise',
        ),
        migrations.AddField(
            model_name='pin',
            name='vr_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroomvr.vrtask'),
            preserve_default=False,
        ),
    ]
