# Generated by Django 3.2 on 2022-03-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomvr', '0010_auto_20220328_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrdelivery',
            name='day_exercise_was_done',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
